// ─── Types ────────────────────────────────────────────────────────────────────

export type CatalogCategory = {
  slug: string;
  name: string;
  accent: string;
  description: string;
  href: string;
  coverImage?: string;
  comingSoon?: boolean;
};

export type CatalogProduct = {
  slug: string;
  name: string;
  shortName: string;
  cardTitle: string;
  categorySlug: string;
  categoryName: string;
  image: string;
  gallery: string[];
  priceLabel: string;
  displayPrice: string;
  priceValue: number;       // numeric BRL — usado no subtotal do carrinho
  sizes: string[];          // padrão BR: ["P","M","G","GG","XG","XGG"] ou kids: ["4","6",...]
  badge: string;
  description: string;
  line?: string;
  status?: string;          // "Novo" | "Pronta entrega" | "Últimas unidades" | "Sob encomenda"
  season?: string;
  isFeatured?: boolean;
  isBestseller?: boolean;
  team?: string;
};

// ─── Categories (7) ──────────────────────────────────────────────────────────

export const catalogCategories: CatalogCategory[] = [
  {
    slug: "nacionais",
    name: "Nacionais",
    accent: "Clubes brasileiros",
    description: "Flamengo, Corinthians, São Paulo, Vasco, Cruzeiro e os maiores do Brasil.",
    href: "/categorias/nacionais",
    coverImage: "/catalog/flamengo-home-26-27/1.jpg",
  },
  {
    slug: "europeias",
    name: "Europeias",
    accent: "Clubes europeus",
    description: "Real Madrid, Barcelona, Arsenal, Bayern, PSG, Milan e mais dos maiores da Europa.",
    href: "/categorias/europeias",
    coverImage: "/catalog/real-madrid-home-26-27/1.jpg",
  },
  {
    slug: "selecoes",
    name: "Seleções",
    accent: "Seleções nacionais",
    description: "Brasil, Argentina, Croácia, Espanha e as grandes seleções da Copa 2026.",
    href: "/categorias/selecoes",
    coverImage: "/catalog/brazil-home-2026/1.jpg",
  },
  {
    slug: "retros",
    name: "Retrôs",
    accent: "Clássicos do futebol",
    description: "Relíquias históricas do futebol mundial. Peças de colecionador com alma de ídolo.",
    href: "/categorias/retros",
    coverImage: "/catalog/palmeiras-retro-1996/1.jpg",
  },
  {
    slug: "femininas",
    name: "Femininas",
    accent: "Linha feminina",
    description: "Baby looks e modelos femininos de times e seleções. Corte pensado para ela.",
    href: "/categorias/femininas",
    coverImage: "/catalog/women-bayern-munich-25-26/1.png",
  },
  {
    slug: "conjuntos",
    name: "Conjuntos",
    accent: "Camisa + short / kit completo",
    description: "Kits completos com camisa e short. Visual fechado, compra única, mais economia.",
    href: "/categorias/conjuntos",
    coverImage: "/catalog/kit-flamengo-adulto-25-26/1.jpg",
  },
  {
    slug: "infantil",
    name: "Infantil",
    accent: "Linha kids",
    description: "Camisas importadas para os pequenos torcedores. Tamanhos de 4 a 14 anos.",
    href: "/categorias/infantil",
    coverImage: "/catalog/barcelona-kids-kit-25-26/1.jpg",
  },
];

// ─── Products ────────────────────────────────────────────────────────────────

export const catalogProducts: CatalogProduct[] = [

  // ── EUROPEIAS ───────────────────────────────────────────────────────────────

  {
    slug: "real-madrid-home-26-27",
    name: "Real Madrid Home 26/27",
    shortName: "Real Madrid 26/27",
    cardTitle: "Real Madrid Home",
    categorySlug: "europeias",
    categoryName: "Europeias",
    image: "/catalog/real-madrid-home-26-27/1.jpg",
    gallery: ["/catalog/real-madrid-home-26-27/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Mais vendido",
    line: "Linha Torcedor",
    status: "Pronta entrega",
    season: "26/27",
    isFeatured: true,
    isBestseller: true,
    team: "Real Madrid",
    description: "A camisa oficial do maior clube do mundo para a temporada 26/27. Tecido importado de alta qualidade, identidade merengue clássica.",
  },
  {
    slug: "barcelona-home-26-27",
    name: "Barcelona Home 26/27",
    shortName: "Barcelona 26/27",
    cardTitle: "Barcelona Home",
    categorySlug: "europeias",
    categoryName: "Europeias",
    image: "/catalog/barcelona-home-26-27/1.jpg",
    gallery: ["/catalog/barcelona-home-26-27/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Lançamento",
    line: "Linha Torcedor",
    status: "Novo",
    season: "26/27",
    isFeatured: true,
    isBestseller: false,
    team: "Barcelona",
    description: "A camisa blaugrana 26/27 com design que une tradição e modernidade. Importada, acabamento premium.",
  },
  {
    slug: "arsenal-home-26-27",
    name: "Arsenal Home 26/27",
    shortName: "Arsenal 26/27",
    cardTitle: "Arsenal Home",
    categorySlug: "europeias",
    categoryName: "Europeias",
    image: "/catalog/arsenal-home-26-27/1.jpg",
    gallery: ["/catalog/arsenal-home-26-27/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Edição quente",
    line: "Linha Torcedor",
    status: "Pronta entrega",
    season: "26/27",
    isFeatured: false,
    isBestseller: true,
    team: "Arsenal",
    description: "O vermelho clássico dos Gunners na temporada 26/27. Camisa importada com identidade forte.",
  },
  {
    slug: "bayern-munich-home-26-27",
    name: "Bayern Munich Home 26/27",
    shortName: "Bayern Munich 26/27",
    cardTitle: "Bayern Munich Home",
    categorySlug: "europeias",
    categoryName: "Europeias",
    image: "/catalog/bayern-munich-home-26-27/1.jpg",
    gallery: ["/catalog/bayern-munich-home-26-27/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Bundesliga",
    line: "Linha Torcedor",
    status: "Pronta entrega",
    season: "26/27",
    isFeatured: false,
    isBestseller: false,
    team: "Bayern Munich",
    description: "O vermelho bávaro da maior potência da Alemanha. Camisa da temporada 26/27 com acabamento importado.",
  },
  {
    slug: "milan-home-26-27",
    name: "Milan Home 26/27",
    shortName: "Milan 26/27",
    cardTitle: "Milan Home",
    categorySlug: "europeias",
    categoryName: "Europeias",
    image: "/catalog/milan-home-26-27/1.jpg",
    gallery: ["/catalog/milan-home-26-27/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Serie A",
    line: "Linha Torcedor",
    status: "Pronta entrega",
    season: "26/27",
    isFeatured: false,
    isBestseller: false,
    team: "Milan",
    description: "O rossonero do Milan na temporada 26/27. Listras icônicas, qualidade de importado.",
  },
  {
    slug: "psg-manga-longa-25-26",
    name: "PSG Manga Longa 25/26",
    shortName: "PSG Manga Longa",
    cardTitle: "PSG Manga Longa",
    categorySlug: "europeias",
    categoryName: "Europeias",
    image: "/catalog/psg-manga-longa-25-26/1.jpg",
    gallery: ["/catalog/psg-manga-longa-25-26/1.jpg"],
    priceLabel: "R$ 139,90",
    displayPrice: "R$ 139,90",
    priceValue: 139.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Especial",
    line: "Manga Longa",
    status: "Últimas unidades",
    season: "25/26",
    isFeatured: true,
    isBestseller: false,
    team: "PSG",
    description: "Versão manga longa da camisa do PSG 25/26. Peça premium com identidade parisiense, acabamento importado.",
  },
  {
    slug: "inter-miami-home-26-27",
    name: "Inter Miami Home 26/27",
    shortName: "Inter Miami 26/27",
    cardTitle: "Inter Miami Home",
    categorySlug: "europeias",
    categoryName: "Europeias",
    image: "/catalog/inter-miami-home-26-27/1.jpg",
    gallery: ["/catalog/inter-miami-home-26-27/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "MLS",
    line: "Linha Torcedor",
    status: "Novo",
    season: "26/27",
    isFeatured: false,
    isBestseller: false,
    team: "Inter Miami",
    description: "A camisa do clube de Messi e Suárez na temporada 26/27. Rosa clássico de Miami, importado.",
  },

  // ── NACIONAIS ───────────────────────────────────────────────────────────────

  {
    slug: "flamengo-home-26-27",
    name: "Flamengo Home 26/27",
    shortName: "Flamengo 26/27",
    cardTitle: "Flamengo Home",
    categorySlug: "nacionais",
    categoryName: "Nacionais",
    image: "/catalog/flamengo-home-26-27/1.jpg",
    gallery: ["/catalog/flamengo-home-26-27/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Mais vendido",
    line: "Linha Torcedor",
    status: "Pronta entrega",
    season: "26/27",
    isFeatured: true,
    isBestseller: true,
    team: "Flamengo",
    description: "A camisa do Mengão 26/27. Preto e vermelho clássico, importada com acabamento premium. Nação Rubro-Negra.",
  },
  {
    slug: "corinthians-home-2026",
    name: "Corinthians Home 2026",
    shortName: "Corinthians 2026",
    cardTitle: "Corinthians Home",
    categorySlug: "nacionais",
    categoryName: "Nacionais",
    image: "/catalog/corinthians-home-2026/1.jpg",
    gallery: ["/catalog/corinthians-home-2026/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Fiel",
    line: "Linha Torcedor",
    status: "Pronta entrega",
    season: "2026",
    isFeatured: true,
    isBestseller: false,
    team: "Corinthians",
    description: "O manto alvinegro do Corinthians para 2026. Identidade Fiel, qualidade importada.",
  },
  {
    slug: "vasco-home-26-27",
    name: "Vasco da Gama Home 26/27",
    shortName: "Vasco 26/27",
    cardTitle: "Vasco Home",
    categorySlug: "nacionais",
    categoryName: "Nacionais",
    image: "/catalog/vasco-home-26-27/1.jpg",
    gallery: ["/catalog/vasco-home-26-27/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Gigante da Colina",
    line: "Linha Torcedor",
    status: "Pronta entrega",
    season: "26/27",
    isFeatured: false,
    isBestseller: true,
    team: "Vasco",
    description: "O manto cruzmaltino da temporada 26/27. Identidade clássica do Vasco, acabamento importado.",
  },
  {
    slug: "sao-paulo-manga-longa-25-26",
    name: "São Paulo Manga Longa 25/26",
    shortName: "São Paulo Manga Longa",
    cardTitle: "São Paulo Manga Longa",
    categorySlug: "nacionais",
    categoryName: "Nacionais",
    image: "/catalog/sao-paulo-manga-longa-25-26/1.jpg",
    gallery: ["/catalog/sao-paulo-manga-longa-25-26/1.jpg"],
    priceLabel: "R$ 139,90",
    displayPrice: "R$ 139,90",
    priceValue: 139.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Especial",
    line: "Manga Longa",
    status: "Últimas unidades",
    season: "25/26",
    isFeatured: false,
    isBestseller: false,
    team: "São Paulo",
    description: "Versão manga longa do Tricolor Paulista 25/26. Peça diferenciada para torcedores exigentes.",
  },

  // ── SELEÇÕES ────────────────────────────────────────────────────────────────

  {
    slug: "brazil-home-2026",
    name: "Brasil Home — Copa do Mundo 2026",
    shortName: "Brasil Home 2026",
    cardTitle: "Brasil Home 2026",
    categorySlug: "selecoes",
    categoryName: "Seleções",
    image: "/catalog/brazil-home-2026/1.jpg",
    gallery: ["/catalog/brazil-home-2026/1.jpg", "/catalog/brazil-home-2026/2.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Copa 2026",
    line: "Cápsula Copa",
    status: "Novo",
    season: "2026",
    isFeatured: true,
    isBestseller: true,
    team: "Brasil",
    description: "A camisa canarinho para a Copa do Mundo 2026. Edição comemorativa importada — peça histórica para torcedores e colecionadores.",
  },
  {
    slug: "argentina-manga-longa-2026",
    name: "Argentina Manga Longa — Copa 2026",
    shortName: "Argentina Manga Longa",
    cardTitle: "Argentina Manga Longa",
    categorySlug: "selecoes",
    categoryName: "Seleções",
    image: "/catalog/argentina-manga-longa-2026/1.jpg",
    gallery: ["/catalog/argentina-manga-longa-2026/1.jpg"],
    priceLabel: "R$ 139,90",
    displayPrice: "R$ 139,90",
    priceValue: 139.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Copa 2026",
    line: "Manga Longa",
    status: "Novo",
    season: "2026",
    isFeatured: true,
    isBestseller: false,
    team: "Argentina",
    description: "A celeste y blanca em versão manga longa para a Copa 2026. Peça diferenciada da campeã do mundo.",
  },
  {
    slug: "croatia-home-2026",
    name: "Croácia Home — Copa do Mundo 2026",
    shortName: "Croácia 2026",
    cardTitle: "Croácia Home 2026",
    categorySlug: "selecoes",
    categoryName: "Seleções",
    image: "/catalog/croatia-home-2026/1.jpg",
    gallery: ["/catalog/croatia-home-2026/1.jpg"],
    priceLabel: "R$ 129,90",
    displayPrice: "R$ 129,90",
    priceValue: 129.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Copa 2026",
    line: "Cápsula Copa",
    status: "Pronta entrega",
    season: "2026",
    isFeatured: false,
    isBestseller: false,
    team: "Croácia",
    description: "O xadrez croata para a Copa 2026. Identidade única, acabamento importado.",
  },
  {
    slug: "spain-retro-2022",
    name: "Espanha Retrô 2022",
    shortName: "Espanha 2022",
    cardTitle: "Espanha Retrô 2022",
    categorySlug: "selecoes",
    categoryName: "Seleções",
    image: "/catalog/spain-retro-2022/1.jpg",
    gallery: ["/catalog/spain-retro-2022/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Colecionador",
    line: "Linha Retrô",
    status: "Últimas unidades",
    season: "2022",
    isFeatured: false,
    isBestseller: false,
    team: "Espanha",
    description: "A camisa da Espanha do ciclo 2022. Peça de colecionador para os fãs da Roja.",
  },

  // ── RETRÔS ──────────────────────────────────────────────────────────────────

  {
    slug: "palmeiras-retro-1996",
    name: "Palmeiras Retrô 1996",
    shortName: "Palmeiras Retrô 96",
    cardTitle: "Palmeiras Retrô 1996",
    categorySlug: "retros",
    categoryName: "Retrôs",
    image: "/catalog/palmeiras-retro-1996/1.jpg",
    gallery: ["/catalog/palmeiras-retro-1996/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Relíquia",
    line: "Linha Retrô",
    status: "Últimas unidades",
    season: "1996",
    isFeatured: true,
    isBestseller: false,
    team: "Palmeiras",
    description: "A camisa histórica do Verdão de 1996 — ano do Brasileiro. Peça de colecionador, tecido premium.",
  },
  {
    slug: "atletico-madrid-retro-03-04",
    name: "Atlético de Madrid Retrô 03/04",
    shortName: "Atlético Madrid 03/04",
    cardTitle: "Atlético Madrid Retrô",
    categorySlug: "retros",
    categoryName: "Retrôs",
    image: "/catalog/atletico-madrid-retro-03-04/1.jpg",
    gallery: ["/catalog/atletico-madrid-retro-03-04/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Retrô",
    line: "Linha Retrô",
    status: "Pronta entrega",
    season: "03/04",
    isFeatured: false,
    isBestseller: false,
    team: "Atlético Madrid",
    description: "O listrado rojiblanco da época clássica do Atleti. Para colecionadores e apaixonados pela história.",
  },
  {
    slug: "chelsea-retro-20-21",
    name: "Chelsea Retrô 20/21",
    shortName: "Chelsea Retrô 20/21",
    cardTitle: "Chelsea Retrô 20/21",
    categorySlug: "retros",
    categoryName: "Retrôs",
    image: "/catalog/chelsea-retro-20-21/1.jpg",
    gallery: ["/catalog/chelsea-retro-20-21/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Retrô",
    line: "Linha Retrô",
    status: "Pronta entrega",
    season: "20/21",
    isFeatured: false,
    isBestseller: false,
    team: "Chelsea",
    description: "O azul de Stamford Bridge da temporada Champions 20/21. Camisa retrô de alto valor para colecionadores.",
  },
  {
    slug: "cruzeiro-retro-93-94",
    name: "Cruzeiro Retrô 93/94",
    shortName: "Cruzeiro Retrô 93/94",
    cardTitle: "Cruzeiro Retrô 93/94",
    categorySlug: "retros",
    categoryName: "Retrôs",
    image: "/catalog/cruzeiro-retro-93-94/1.jpg",
    gallery: ["/catalog/cruzeiro-retro-93-94/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Relíquia",
    line: "Linha Retrô",
    status: "Últimas unidades",
    season: "93/94",
    isFeatured: false,
    isBestseller: false,
    team: "Cruzeiro",
    description: "O manto celeste do Cruzeiro bicampeão da Libertadores 93/94. Relíquia azul para apaixonados.",
  },
  {
    slug: "psg-retro-21-22",
    name: "PSG Retrô 21/22",
    shortName: "PSG Retrô 21/22",
    cardTitle: "PSG Retrô 21/22",
    categorySlug: "retros",
    categoryName: "Retrôs",
    image: "/catalog/psg-retro-21-22/1.jpg",
    gallery: ["/catalog/psg-retro-21-22/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Retrô",
    line: "Linha Retrô",
    status: "Pronta entrega",
    season: "21/22",
    isFeatured: false,
    isBestseller: false,
    team: "PSG",
    description: "O azul noturno do PSG da era Messi, Neymar e Mbappé. Para quem viveu aquele time.",
  },
  {
    slug: "tottenham-retro-18-19",
    name: "Tottenham Retrô 18/19",
    shortName: "Tottenham Retrô 18/19",
    cardTitle: "Tottenham Retrô 18/19",
    categorySlug: "retros",
    categoryName: "Retrôs",
    image: "/catalog/tottenham-retro-18-19/1.jpg",
    gallery: ["/catalog/tottenham-retro-18-19/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Retrô",
    line: "Linha Retrô",
    status: "Pronta entrega",
    season: "18/19",
    isFeatured: false,
    isBestseller: false,
    team: "Tottenham",
    description: "A camisa dos Spurs da final da Champions League 18/19. Peça histórica para fãs do clube londrino.",
  },
  {
    slug: "porto-retro-13-14",
    name: "Porto Retrô 13/14",
    shortName: "Porto Retrô 13/14",
    cardTitle: "Porto Retrô 13/14",
    categorySlug: "retros",
    categoryName: "Retrôs",
    image: "/catalog/porto-retro-13-14/1.jpg",
    gallery: ["/catalog/porto-retro-13-14/1.jpg"],
    priceLabel: "R$ 109,90",
    displayPrice: "R$ 109,90",
    priceValue: 109.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Retrô",
    line: "Linha Retrô",
    status: "Pronta entrega",
    season: "13/14",
    isFeatured: false,
    isBestseller: false,
    team: "Porto",
    description: "O azul dragão do Porto da temporada 13/14. Identidade lusa clássica para colecionadores.",
  },
  {
    slug: "boca-juniors-retro-20-21",
    name: "Boca Juniors Retrô 20/21",
    shortName: "Boca Juniors 20/21",
    cardTitle: "Boca Juniors Retrô",
    categorySlug: "retros",
    categoryName: "Retrôs",
    image: "/catalog/boca-juniors-retro-20-21/1.jpg",
    gallery: ["/catalog/boca-juniors-retro-20-21/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "La Bombonera",
    line: "Linha Retrô",
    status: "Últimas unidades",
    season: "20/21",
    isFeatured: false,
    isBestseller: false,
    team: "Boca Juniors",
    description: "A camisa xeneize 20/21 — azul e ouro de La Bombonera. Para quem ama o futebol sul-americano.",
  },

  // ── FEMININAS ───────────────────────────────────────────────────────────────

  {
    slug: "women-bayern-munich-25-26",
    name: "Bayern Munich Feminina 25/26",
    shortName: "Bayern Feminina 25/26",
    cardTitle: "Bayern Munich Feminina",
    categorySlug: "femininas",
    categoryName: "Femininas",
    image: "/catalog/women-bayern-munich-25-26/1.png",
    gallery: ["/catalog/women-bayern-munich-25-26/1.png"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG"],
    badge: "Feminina",
    line: "Linha Feminina",
    status: "Novo",
    season: "25/26",
    isFeatured: true,
    isBestseller: false,
    team: "Bayern Munich",
    description: "Camisa feminina do Bayern Munich 25/26. Corte e caimento pensados para ela, qualidade importada.",
  },
  {
    slug: "women-gremio-25-26",
    name: "Grêmio Feminina 25/26",
    shortName: "Grêmio Feminina",
    cardTitle: "Grêmio Feminina",
    categorySlug: "femininas",
    categoryName: "Femininas",
    image: "/catalog/women-gremio-25-26/1.jpg",
    gallery: ["/catalog/women-gremio-25-26/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG"],
    badge: "Feminina",
    line: "Linha Feminina",
    status: "Novo",
    season: "25/26",
    isFeatured: false,
    isBestseller: false,
    team: "Grêmio",
    description: "O tricolor gaúcho em versão feminina 25/26. Para as guerreiras gremistas.",
  },
  {
    slug: "bahia-feminina-24-25",
    name: "Bahia Feminina 24/25",
    shortName: "Bahia Feminina",
    cardTitle: "Bahia Feminina",
    categorySlug: "femininas",
    categoryName: "Femininas",
    image: "/catalog/bahia-feminina-24-25/1.jpg",
    gallery: ["/catalog/bahia-feminina-24-25/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG"],
    badge: "Feminina",
    line: "Linha Feminina",
    status: "Pronta entrega",
    season: "24/25",
    isFeatured: false,
    isBestseller: false,
    team: "Bahia",
    description: "O azul, vermelho e branco do Bahia em versão feminina 24/25.",
  },
  {
    slug: "internacional-baby-look-26-27",
    name: "Internacional Baby Look 26/27",
    shortName: "Internacional Baby Look",
    cardTitle: "Internacional Baby Look",
    categorySlug: "femininas",
    categoryName: "Femininas",
    image: "/catalog/internacional-baby-look-26-27/1.jpg",
    gallery: ["/catalog/internacional-baby-look-26-27/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG"],
    badge: "Baby Look",
    line: "Baby Look",
    status: "Novo",
    season: "26/27",
    isFeatured: false,
    isBestseller: false,
    team: "Internacional",
    description: "Baby look do Internacional 26/27 — para torcedoras coloradas estilosas.",
  },
  {
    slug: "portugal-baby-look-2026",
    name: "Portugal Baby Look 2026",
    shortName: "Portugal Baby Look",
    cardTitle: "Portugal Baby Look",
    categorySlug: "femininas",
    categoryName: "Femininas",
    image: "/catalog/portugal-baby-look-2026/1.jpg",
    gallery: ["/catalog/portugal-baby-look-2026/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG"],
    badge: "Baby Look",
    line: "Baby Look",
    status: "Novo",
    season: "2026",
    isFeatured: false,
    isBestseller: false,
    team: "Portugal",
    description: "Baby look da Seleção de Portugal Copa 2026 — vermelho e verde com estilo.",
  },
  {
    slug: "sao-paulo-baby-look-26-27",
    name: "São Paulo Baby Look 26/27",
    shortName: "São Paulo Baby Look",
    cardTitle: "São Paulo Baby Look",
    categorySlug: "femininas",
    categoryName: "Femininas",
    image: "/catalog/sao-paulo-baby-look-26-27/1.jpg",
    gallery: ["/catalog/sao-paulo-baby-look-26-27/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["P", "M", "G", "GG"],
    badge: "Baby Look",
    line: "Baby Look",
    status: "Pronta entrega",
    season: "26/27",
    isFeatured: false,
    isBestseller: false,
    team: "São Paulo",
    description: "Baby look do São Paulo 26/27 — para torcedoras que querem representar com estilo.",
  },

  // ── CONJUNTOS ───────────────────────────────────────────────────────────────

  {
    slug: "kit-flamengo-adulto-25-26",
    name: "Kit Flamengo Adulto 25/26 — Camisa + Short",
    shortName: "Kit Flamengo 25/26",
    cardTitle: "Kit Flamengo Adulto",
    categorySlug: "conjuntos",
    categoryName: "Conjuntos",
    image: "/catalog/kit-flamengo-adulto-25-26/1.jpg",
    gallery: ["/catalog/kit-flamengo-adulto-25-26/1.jpg"],
    priceLabel: "R$ 169,90",
    displayPrice: "R$ 169,90",
    priceValue: 169.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Kit completo",
    line: "Conjunto",
    status: "Pronta entrega",
    season: "25/26",
    isFeatured: true,
    isBestseller: true,
    team: "Flamengo",
    description: "Kit completo Flamengo 25/26 — camisa + short juntos. Rubro-negro do início ao fim, visual fechado.",
  },
  {
    slug: "kit-real-madrid-adulto-25-26",
    name: "Kit Real Madrid Adulto 25/26 — Camisa + Short",
    shortName: "Kit Real Madrid 25/26",
    cardTitle: "Kit Real Madrid Adulto",
    categorySlug: "conjuntos",
    categoryName: "Conjuntos",
    image: "/catalog/kit-real-madrid-adulto-25-26/1.jpg",
    gallery: ["/catalog/kit-real-madrid-adulto-25-26/1.jpg"],
    priceLabel: "R$ 169,90",
    displayPrice: "R$ 169,90",
    priceValue: 169.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Kit completo",
    line: "Conjunto",
    status: "Pronta entrega",
    season: "25/26",
    isFeatured: true,
    isBestseller: false,
    team: "Real Madrid",
    description: "Kit completo Real Madrid 25/26 — camisa + short. Visual merengue do início ao fim.",
  },
  {
    slug: "kit-barcelona-agasalho-25-26",
    name: "Kit Barcelona Agasalho 25/26",
    shortName: "Agasalho Barcelona 25/26",
    cardTitle: "Kit Barcelona Agasalho",
    categorySlug: "conjuntos",
    categoryName: "Conjuntos",
    image: "/catalog/kit-barcelona-agasalho-25-26/1.jpg",
    gallery: ["/catalog/kit-barcelona-agasalho-25-26/1.jpg"],
    priceLabel: "R$ 189,90",
    displayPrice: "R$ 189,90",
    priceValue: 189.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Agasalho",
    line: "Agasalho",
    status: "Últimas unidades",
    season: "25/26",
    isFeatured: false,
    isBestseller: false,
    team: "Barcelona",
    description: "Agasalho completo do Barcelona 25/26 — jaqueta + calça. Para os dias frios com identidade blaugrana.",
  },
  {
    slug: "kit-psg-agasalho-25-26",
    name: "Kit PSG Agasalho 25/26",
    shortName: "Agasalho PSG 25/26",
    cardTitle: "Kit PSG Agasalho",
    categorySlug: "conjuntos",
    categoryName: "Conjuntos",
    image: "/catalog/kit-psg-agasalho-25-26/1.jpg",
    gallery: ["/catalog/kit-psg-agasalho-25-26/1.jpg"],
    priceLabel: "R$ 189,90",
    displayPrice: "R$ 189,90",
    priceValue: 189.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Agasalho",
    line: "Agasalho",
    status: "Novo",
    season: "25/26",
    isFeatured: false,
    isBestseller: false,
    team: "PSG",
    description: "Agasalho do PSG 25/26 — identidade parisiense para os dias frios. Importado, acabamento premium.",
  },
  {
    slug: "kit-corinthians-treino-25-26",
    name: "Kit Corinthians Treino 25/26",
    shortName: "Kit Treino Corinthians",
    cardTitle: "Kit Corinthians Treino",
    categorySlug: "conjuntos",
    categoryName: "Conjuntos",
    image: "/catalog/kit-corinthians-treino-25-26/1.jpg",
    gallery: ["/catalog/kit-corinthians-treino-25-26/1.jpg"],
    priceLabel: "R$ 159,90",
    displayPrice: "R$ 159,90",
    priceValue: 159.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Treino",
    line: "Conjunto Treino",
    status: "Pronta entrega",
    season: "25/26",
    isFeatured: false,
    isBestseller: false,
    team: "Corinthians",
    description: "Kit de treino alvinegro 25/26 — camiseta + calça. Para treinar com a identidade Fiel.",
  },
  {
    slug: "kit-cruzeiro-adulto-25-26",
    name: "Kit Cruzeiro Adulto 25/26",
    shortName: "Kit Cruzeiro 25/26",
    cardTitle: "Kit Cruzeiro Adulto",
    categorySlug: "conjuntos",
    categoryName: "Conjuntos",
    image: "/catalog/kit-cruzeiro-adulto-25-26/1.jpg",
    gallery: ["/catalog/kit-cruzeiro-adulto-25-26/1.jpg"],
    priceLabel: "R$ 159,90",
    displayPrice: "R$ 159,90",
    priceValue: 159.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Kit completo",
    line: "Conjunto",
    status: "Pronta entrega",
    season: "25/26",
    isFeatured: false,
    isBestseller: false,
    team: "Cruzeiro",
    description: "Kit completo Cruzeiro 25/26 — camisa + short. O celeste estrelado em visual completo.",
  },
  {
    slug: "kit-santos-adulto-24-25",
    name: "Kit Santos Adulto 24/25",
    shortName: "Kit Santos 24/25",
    cardTitle: "Kit Santos Adulto",
    categorySlug: "conjuntos",
    categoryName: "Conjuntos",
    image: "/catalog/kit-santos-adulto-24-25/1.jpg",
    gallery: ["/catalog/kit-santos-adulto-24-25/1.jpg"],
    priceLabel: "R$ 159,90",
    displayPrice: "R$ 159,90",
    priceValue: 159.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Kit completo",
    line: "Conjunto",
    status: "Últimas unidades",
    season: "24/25",
    isFeatured: false,
    isBestseller: false,
    team: "Santos",
    description: "Kit completo Santos 24/25 — camisa + short. O branco do Peixe em visual fechado.",
  },
  {
    slug: "shorts-brazil-2026",
    name: "Short Brasil Home — Copa 2026",
    shortName: "Short Brasil 2026",
    cardTitle: "Short Brasil Home",
    categorySlug: "conjuntos",
    categoryName: "Conjuntos",
    image: "/catalog/shorts-brazil-2026/1.jpg",
    gallery: ["/catalog/shorts-brazil-2026/1.jpg"],
    priceLabel: "R$ 89,90",
    displayPrice: "R$ 89,90",
    priceValue: 89.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Peça avulsa",
    line: "Peça Avulsa",
    status: "Pronta entrega",
    season: "2026",
    isFeatured: false,
    isBestseller: false,
    team: "Brasil",
    description: "Short oficial da Seleção Brasileira Copa 2026. Composição perfeita com a camisa canarinho.",
  },
  {
    slug: "shorts-spain-2026",
    name: "Short Espanha — Copa 2026",
    shortName: "Short Espanha 2026",
    cardTitle: "Short Espanha 2026",
    categorySlug: "conjuntos",
    categoryName: "Conjuntos",
    image: "/catalog/shorts-spain-2026/1.jpg",
    gallery: ["/catalog/shorts-spain-2026/1.jpg"],
    priceLabel: "R$ 89,90",
    displayPrice: "R$ 89,90",
    priceValue: 89.90,
    sizes: ["P", "M", "G", "GG", "XG", "XGG"],
    badge: "Peça avulsa",
    line: "Peça Avulsa",
    status: "Pronta entrega",
    season: "2026",
    isFeatured: false,
    isBestseller: false,
    team: "Espanha",
    description: "Short da Espanha Copa 2026. Perfeito com a camisa da Roja ou como peça avulsa.",
  },

  // ── INFANTIL ────────────────────────────────────────────────────────────────

  {
    slug: "barcelona-kids-kit-25-26",
    name: "Barcelona Kids Kit 25/26",
    shortName: "Barcelona Kids 25/26",
    cardTitle: "Barcelona Kids Kit",
    categorySlug: "infantil",
    categoryName: "Infantil",
    image: "/catalog/barcelona-kids-kit-25-26/1.jpg",
    gallery: ["/catalog/barcelona-kids-kit-25-26/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["4", "6", "8", "10", "12", "14"],
    badge: "Kids",
    line: "Linha Kids",
    status: "Pronta entrega",
    season: "25/26",
    isFeatured: true,
    isBestseller: false,
    team: "Barcelona",
    description: "Kit infantil do Barcelona 25/26 — camisa + short. Para os pequenos torcedores blaugranas.",
  },
  {
    slug: "flamengo-kids-25-26",
    name: "Flamengo Kids Manga Longa 25/26",
    shortName: "Flamengo Kids ML",
    cardTitle: "Flamengo Kids Manga Longa",
    categorySlug: "infantil",
    categoryName: "Infantil",
    image: "/catalog/flamengo-kids-25-26/1.jpg",
    gallery: ["/catalog/flamengo-kids-25-26/1.jpg"],
    priceLabel: "R$ 109,90",
    displayPrice: "R$ 109,90",
    priceValue: 109.90,
    sizes: ["4", "6", "8", "10", "12", "14"],
    badge: "Kids",
    line: "Linha Kids",
    status: "Novo",
    season: "25/26",
    isFeatured: false,
    isBestseller: false,
    team: "Flamengo",
    description: "Camisa manga longa do Flamengo infantil 25/26. Para os pequenos rubro-negros com muito estilo.",
  },
  {
    slug: "al-nassr-kids-25-26",
    name: "Al-Nassr Kids Home 25/26",
    shortName: "Al-Nassr Kids 25/26",
    cardTitle: "Al-Nassr Kids Home",
    categorySlug: "infantil",
    categoryName: "Infantil",
    image: "/catalog/al-nassr-kids-25-26/1.jpg",
    gallery: ["/catalog/al-nassr-kids-25-26/1.jpg"],
    priceLabel: "R$ 109,90",
    displayPrice: "R$ 109,90",
    priceValue: 109.90,
    sizes: ["4", "6", "8", "10", "12", "14"],
    badge: "Kids",
    line: "Linha Kids",
    status: "Novo",
    season: "25/26",
    isFeatured: false,
    isBestseller: false,
    team: "Al-Nassr",
    description: "Camisa infantil do Al-Nassr 25/26 — o clube de Cristiano Ronaldo. Para os pequenos fãs do CR7.",
  },
  {
    slug: "italy-kids-kit-2026",
    name: "Itália Kids Kit Copa 2026",
    shortName: "Itália Kids 2026",
    cardTitle: "Itália Kids Kit",
    categorySlug: "infantil",
    categoryName: "Infantil",
    image: "/catalog/italy-kids-kit-2026/1.jpg",
    gallery: ["/catalog/italy-kids-kit-2026/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["4", "6", "8", "10", "12", "14"],
    badge: "Copa 2026",
    line: "Linha Kids",
    status: "Pronta entrega",
    season: "2026",
    isFeatured: false,
    isBestseller: false,
    team: "Itália",
    description: "Kit infantil da Itália Copa 2026 — camisa + short. O azul azzurro para os pequenos.",
  },
  {
    slug: "sao-paulo-kids-kit-26-27",
    name: "São Paulo Kids Kit 26/27",
    shortName: "São Paulo Kids 26/27",
    cardTitle: "São Paulo Kids Kit",
    categorySlug: "infantil",
    categoryName: "Infantil",
    image: "/catalog/sao-paulo-kids-kit-26-27/1.jpg",
    gallery: ["/catalog/sao-paulo-kids-kit-26-27/1.jpg"],
    priceLabel: "R$ 119,90",
    displayPrice: "R$ 119,90",
    priceValue: 119.90,
    sizes: ["4", "6", "8", "10", "12", "14"],
    badge: "Kids",
    line: "Linha Kids",
    status: "Novo",
    season: "26/27",
    isFeatured: false,
    isBestseller: false,
    team: "São Paulo",
    description: "Kit infantil do São Paulo 26/27. Para os pequenos tricolores paulistas.",
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getProductBySlug(slug: string) {
  return catalogProducts.find((p) => p.slug === slug);
}

export function getCategoryBySlug(slug: string) {
  return catalogCategories.find((c) => c.slug === slug);
}

export function getProductsByCategory(slug: string) {
  return catalogProducts.filter((p) => p.categorySlug === slug);
}

export function getFeaturedProducts() {
  return catalogProducts.filter((p) => p.isFeatured);
}

export function getBestsellerProducts() {
  return catalogProducts.filter((p) => p.isBestseller);
}

export function searchProducts(query: string): CatalogProduct[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return catalogProducts.filter((p) =>
    [p.name, p.cardTitle, p.shortName, p.categoryName, p.badge, p.line ?? "", p.season ?? "", p.team ?? ""]
      .some((field) => field.toLowerCase().includes(q))
  );
}
