// One-off helper that reads the static catalog and emits an idempotent SQL
// seed for Supabase. Run with:
//   npx tsx scripts/generate-catalog-seed.ts > supabase/migrations/<ts>_seed_catalog.sql
//
// Output structure:
//   1. categories — one row per CatalogCategory (active=!comingSoon)
//   2. products  — one row per CatalogProduct, rich fields parked in metadata
//   3. product_images — one row per gallery entry, position 0..n
//
// All inserts use ON CONFLICT (store_id, slug) DO NOTHING so re-running is
// safe; if the constraint doesn't exist yet, the migration adds it first.

import {
  catalogCategories,
  catalogProducts,
  type CatalogProduct,
} from "../src/themes/thailandia/content/catalog";

const STORE_ID = "24d7ba71-21c3-4d19-901a-dcef43aacd89";
const DEFAULT_STOCK = 50;

function sqlString(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

function jsonbLiteral(value: unknown): string {
  return sqlString(JSON.stringify(value)) + "::jsonb";
}

function productMetadata(p: CatalogProduct) {
  return {
    sizes: p.sizes,
    badge: p.badge,
    line: p.line ?? null,
    status: p.status ?? null,
    season: p.season ?? null,
    isBestseller: p.isBestseller ?? false,
    team: p.team ?? null,
    region: p.region ?? null,
    collection: p.collection ?? null,
    league: p.league ?? null,
    tags: p.tags ?? [],
    shortName: p.shortName,
    cardTitle: p.cardTitle,
    priceLabel: p.priceLabel,
    displayPrice: p.displayPrice,
  };
}

function emit() {
  const lines: string[] = [];
  lines.push("-- Auto-generated by scripts/generate-catalog-seed.ts");
  lines.push("-- Idempotent: ON CONFLICT (store_id, slug) DO NOTHING.");
  lines.push("");

  // Unique indexes (Postgres supports IF NOT EXISTS on indexes; ON CONFLICT
  // accepts a unique index target, no separate constraint required).
  lines.push("-- 0. Unique indexes for idempotent ON CONFLICT");
  lines.push(`create unique index if not exists categories_store_slug_unique on public.categories (store_id, slug);`);
  lines.push(`create unique index if not exists products_store_slug_unique   on public.products   (store_id, slug);`);
  lines.push("");

  // Categories
  lines.push("-- 1. Categories");
  lines.push("insert into public.categories (store_id, slug, name, description, position, active)");
  lines.push("values");
  const catRows = catalogCategories.map((c, i) =>
    `  (${sqlString(STORE_ID)}::uuid, ${sqlString(c.slug)}, ${sqlString(c.name)}, ${sqlString(c.description)}, ${i + 1}, ${c.comingSoon ? "false" : "true"})`
  );
  lines.push(catRows.join(",\n"));
  lines.push("on conflict (store_id, slug) do nothing;");
  lines.push("");

  // Products
  lines.push("-- 2. Products");
  lines.push("insert into public.products (store_id, category_id, slug, name, description, price, featured, active, stock_quantity, metadata)");
  lines.push("select");
  lines.push(`  ${sqlString(STORE_ID)}::uuid,`);
  lines.push(`  c.id,`);
  lines.push(`  x.slug, x.name, x.description, x.price, x.featured, true, ${DEFAULT_STOCK}, x.metadata`);
  lines.push("from jsonb_to_recordset(");
  const prodJson = catalogProducts.map((p) => ({
    slug: p.slug,
    name: p.name,
    description: p.description,
    price: p.priceValue,
    featured: p.isFeatured ?? false,
    category_slug: p.categorySlug,
    metadata: productMetadata(p),
  }));
  lines.push("  " + jsonbLiteral(prodJson));
  lines.push(") as x(slug text, name text, description text, price numeric, featured boolean, category_slug text, metadata jsonb)");
  lines.push(`join public.categories c on c.store_id = ${sqlString(STORE_ID)}::uuid and c.slug = x.category_slug`);
  lines.push("on conflict (store_id, slug) do nothing;");
  lines.push("");

  // Product images
  lines.push("-- 3. Product images (gallery)");
  const imageRows: { slug: string; url: string; position: number }[] = [];
  for (const p of catalogProducts) {
    const gallery = p.gallery && p.gallery.length > 0 ? p.gallery : [p.image];
    gallery.forEach((url, i) => imageRows.push({ slug: p.slug, url, position: i }));
  }
  lines.push("insert into public.product_images (product_id, url, position)");
  lines.push("select p.id, x.url, x.position");
  lines.push("from jsonb_to_recordset(");
  lines.push("  " + jsonbLiteral(imageRows));
  lines.push(") as x(slug text, url text, position int)");
  lines.push(`join public.products p on p.store_id = ${sqlString(STORE_ID)}::uuid and p.slug = x.slug`);
  lines.push("where not exists (");
  lines.push("  select 1 from public.product_images pi");
  lines.push("  where pi.product_id = p.id and pi.url = x.url");
  lines.push(");");

  return lines.join("\n");
}

console.log(emit());
